- name: run the playbook tasks on the localhost
  hosts: localhost
  connection: local
  tasks:
  - name: Tweak GRUB
    import_tasks: tasks/grub.yaml

  - name: Enable periodic SSD trim
    become: yes
    systemd:
        name: fstrim.timer
        enabled: yes
        state: started

  - name: Setup yubikey
    import_tasks: tasks/yubikey.yaml 

  - name: Enable natural scrolling
    become: yes
    blockinfile:
        path: /etc/X11/xorg.conf.d/30-touchpad.conf
        insertafter: "Option \"Tapping\" \"on\""
        block: |
          "Option" "NaturalScrolling" "true"

  - name: Setup NVidia/Bumblebee
    import_tasks: tasks/bumblebee.yaml

  - name: Setup TLP
    import_tasks: tasks/tlp.yaml  
    
  - name: Setup SSHD
    import_tasks: tasks/sshd.yaml

  - name: Install script for auto-timezone adjustment
    become: yes
    copy:
        src: files/update-tz.sh
        dest: /etc/NetworkManager/dispatcher.d/09-timezone
        mode: 0755