- name: run the playbook tasks on the localhost
  hosts: localhost
  connection: local
  vars:
    is_matebookx: "{{ ansible_facts['product_name'] == 'MACH-WX9' }}"
  tasks:
  - name: Tweak GRUB
    when: is_matebookx|bool
    import_tasks: tasks/grub.yaml

  - name: Enable periodic SSD trim
    become: yes
    systemd:
        name: fstrim.timer
        enabled: yes
        state: started

  - name: Setup yubikey
    import_tasks: tasks/yubikey.yaml 

  - name: Enable natural scrolling
    become: yes
    blockinfile:
        path: /etc/X11/xorg.conf.d/30-touchpad.conf
        insertafter: "Option \"Tapping\" \"on\""
        block: |
          "Option" "NaturalScrolling" "true"

  - name: Setup NVidia/Bumblebee
    when: is_matebookx|bool
    import_tasks: tasks/bumblebee.yaml

  - name: Setup TLP
    when: is_matebookx|bool
    import_tasks: tasks/tlp.yaml  
    
  - name: Setup SSHD
    import_tasks: tasks/sshd.yaml

  - name: Install script for auto-timezone adjustment
    become: yes
    copy:
        src: files/update-tz.sh
        dest: /etc/NetworkManager/dispatcher.d/09-timezone
        mode: 0755

  - name: Install yay for AUR support
    pacman: name=yay state=present
        
  - name: Install common packages
    yay:
        name:
        - go
        - go-tools
        - xorg-xbacklight
        - redshift
        - unzip
        - zip
        - spotify
        - goland
        - visual-studio-code-bin
        - xss-lock
        - zoom
        - firefox
        - google-chrome
        - ttf-croscore
        - ttf-dejavu
        - ttf-mac-fonts
        - ttf-google-fonts-git>=r1377
        - ttf-ms-fonts
        - dnsutils
        - pkgfile
        - zeal
        - franz

  - name: Apply user config
    import_tasks: tasks/userconfig.yaml