- name: run the playbook tasks on the localhost
  hosts: localhost
  connection: local
  vars:
    is_matebookx: "{{ ansible_facts['product_name'] == 'MACH-WX9' }}"
    xorg_dpi: "{% if is_matebookx %}200{% else %}110{% endif %}"

  tasks:
  - name: Install yay for AUR support
    pacman: name=yay state=present

  - name: Enable periodic SSD trim
    become: yes
    systemd:
        name: fstrim.timer
        enabled: yes
        state: started

  - name: Setup yubikey
    import_tasks: tasks/yubikey.yaml 

  - name: Setup SSHD
    import_tasks: tasks/sshd.yaml

  - name: Install script for auto-timezone adjustment
    become: yes
    copy:
        src: files/update-tz.sh
        dest: /etc/NetworkManager/dispatcher.d/09-timezone
        mode: 0755    

  - name: Setup desktop
    when: not is_matebookx|bool
    include_tasks: tasks/desktop.yaml

  - name: Setup MatebookX
    when: is_matebookx|bool
    include_tasks: tasks/matebookx.yaml

  - name: Install fonts
    yay:
      name:
        - ttf-croscore
        - ttf-dejavu
        - ttf-mac-fonts
        - ttf-ms-fonts
        - ttf-anonymous-pro
        - ttf-cardo
        - ttf-roboto-mono
        - ttf-oxygen
        - ttf-opensans
        
  - name: Install common packages
    yay:
        name:
        - go
        - go-tools
        - xorg-xbacklight
        - redshift
        - unzip
        - zip
        - spotify
        - goland
        - visual-studio-code-bin
        - xss-lock
        - zoom
        - firefox
        - google-chrome
        - dnsutils
        - pkgfile
        - zeal
        - franz
        - op

  - name: Apply user config
    import_tasks: tasks/userconfig.yaml
