- name: run the playbook tasks on the localhost
  hosts: localhost
  connection: local
  vars:
    is_notebook: "{{ ansible_facts['product_name'] == 'MACH-WX9' or ansible_facts['system_vendor'] == 'LENOVO' }}"
    xorg_dpi: "{% if is_notebook %}200{% else %}110{% endif %}"

  tasks:
  - name: Install yay for AUR support
    pacman: name=yay state=present

  - name: Setup desktop
    when: not is_notebook|bool
    include_tasks: tasks/desktop.yaml

  - name: Setup notebook
    when: is_notebook|bool
    include_tasks: tasks/notebook.yaml

  - name: Enable periodic SSD trim
    become: yes
    systemd:
        name: fstrim.timer
        enabled: yes
        state: started

  - name: Setup yubikey
    import_tasks: tasks/yubikey.yaml 

  - name: Setup SSHD
    import_tasks: tasks/sshd.yaml

  - name: Enable NTP
    become: yes
    command: timedatectl set-ntp true

  - name: Install script for auto-timezone adjustment
    become: yes
    copy:
        src: files/update-tz.sh
        dest: /etc/NetworkManager/dispatcher.d/09-timezone
        mode: 0755    

  - name: Install script for VPN fixup
    become: yes
    copy:
        src: files/fixvpn.sh
        dest: /etc/NetworkManager/dispatcher.d/08-fixvpn
        mode: 0755

  - name: Enable natural scrolling
    become: yes
    lineinfile:
        path: /etc/X11/xorg.conf.d/30-touchpad.conf
        regexp: "NaturalScrolling"
        line: "    Option \"NaturalScrolling\" \"true\""
        insertbefore: "^EndSection"

  - name: Enable touchpad while typing
    become: yes
    lineinfile:
        path: /etc/X11/xorg.conf.d/30-touchpad.conf
        regexp: "DisableWhileTyping"
        line: "    Option \"DisableWhileTyping\" \"false\""
        insertbefore: "^EndSection"

  - name: Set default terminal font
    become: yes
    lineinfile:
        path: /etc/vconsole.conf
        regexp: "FONT="
        line: "FONT=ter-v32n"

  - name: Install fonts
    yay:
      name:
        - ttf-anonymous-pro
        - ttf-cardo
        - ttf-croscore
        - ttf-dejavu
        - ttf-mac-fonts
        - ttf-ms-fonts
        - ttf-opensans
        - ttf-oxygen
        - ttf-roboto-mono
        - terminus-font
        
  - name: Install common packages
    yay:
        name:
        - aws-cli
        - brave
        - docker
        - dnsutils
        - firefox
        - franz
        - go
        - go-tools
        - goland
        - google-chrome
        - pkgfile
        - redshift
        - spotify
        - unzip
        - visual-studio-code-bin
        - xorg-xbacklight
        - xss-lock
        - zeal
        - zip
        - zoom

  - name: Apply user config
    import_tasks: tasks/userconfig.yaml

  - name: Set git user/email
    shell: >
      git config --global user.email "dizzyd@dizzyd.com" &&
      git config --global user.name "Dave Smith"    

  - name: Enable docker service
    become: yes
    systemd:
      name: docker.service
      enabled: yes
      state: started

  - name: Add myself to docker group
    become: yes
    command: gpasswd -a dizzyd docker
