- name: Install NVidia and Bumblebee packages
  pacman:
    name:
      - bumblebee
      - bbswitch
      - nvidia
      - mesa
      - acpi_call
      - lib32-virtualgl
      - lib32-nvidia-utils
    state: present

- name: Enable bumblebeed.service
  systemd:
    name: bumblebeed.service
    enabled: yes

- name: Add user to appropriate group
  become: yes
  command: gpasswd -a dizzyd bumblebee

- name: Enable bumblebee driver switching
  become: yes
  ini_file:
    path: /etc/bumblebee/bumblebee.conf
    section: driver-nvidia
    option: PMMethod
    value: bbswitch
