- name: Add pcie_aspm flag to grub
  become: yes
  lineinfile:
    path: /etc/default/grub
    regex: "^GRUB_CMDLINE_LINUX="
    line: "GRUB_CMDLINE_LINUX=\"pcie_aspm=force\""

- name: Regenerate grub
  become: yes
  command: grub-mkconfig -o /boot/grub/grub.conf

