
## NVidia configuration
- name: Install NVidia and Bumblebee packages
  pacman:
    name:
      - bumblebee
      - bbswitch
      - nvidia
      - mesa
      - acpi_call
      - lib32-virtualgl
      - lib32-nvidia-utils
    state: present

- name: Use mhwd to install base drivers
  become: yes
  shell: mhwd -a pci nonfree 0300

- name: Enable bumblebeed.service
  systemd:
    name: bumblebeed.service
    enabled: yes

- name: Add user to appropriate group
  become: yes
  command: gpasswd -a dizzyd bumblebee

- name: Enable bumblebee driver switching
  become: yes
  ini_file:
    path: /etc/bumblebee/bumblebee.conf
    section: driver-nvidia
    option: PMMethod
    value: bbswitch

## Configure power management system
- name: Setup TLP
  import_tasks: tasks/tlp.yaml  

## Force PCIE ASPM for power efficiency
- name: Add pcie_aspm flag to grub
  become: yes
  lineinfile:
    path: /etc/default/grub
    regex: "^GRUB_CMDLINE_LINUX="
    line: "GRUB_CMDLINE_LINUX=\"pcie_aspm=force\""

- name: Regenerate grub
  become: yes
  command: update-grub

