
- name: Use mhwd to install base drivers
  become: yes
  shell: mhwd -a pci nonfree 0300

- name: Enable bumblebeed.service
  systemd:
    name: bumblebeed.service
    enabled: yes

- name: Add user to appropriate group
  become: yes
  command: gpasswd -a dizzyd bumblebee

- name: Enable bumblebee driver switching
  become: yes
  ini_file:
    path: /etc/bumblebee/bumblebee.conf
    section: driver-nvidia
    option: PMMethod
    value: bbswitch

- name: Enable trackpad acceleration
  become: yes
  lineinfile:
      path: /etc/X11/xorg.conf.d/30-touchpad.conf
      regexp: "AccelSpeed"
      line: "    Option \"AccelSpeed\" \"0.6\""
      insertbefore: "^EndSection"

- name: Enforce DRIv2 for intel driver
  become: yes
  lineinfile:
      path: /etc/X11/xorg.conf.d/90-mhwd.conf
      regexp: "Option.+DRI"
      line: "\tOption\t\"DRI\" \"2\""
      insertbefore: "^EndSection"
      backup: yes

## Configure power management system
- name: Setup TLP
  import_tasks: tasks/tlp.yaml  

## Make sure battery module is part of initramfs
- name: Include battery module in initramfs
  become: yes
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: "MODULES="
    line: "MODULES=(battery)"

- name: Rebuild initramfs
  become: yes
  command: mkinitcpio -P

## Force PCIE ASPM for power efficiency
- name: Add pcie_aspm flag to grub
  become: yes
  lineinfile:
    path: /etc/default/grub
    regex: "^GRUB_CMDLINE_LINUX="
    line: "GRUB_CMDLINE_LINUX=\"pcie_aspm=force\""

- name: Regenerate grub
  become: yes
  command: update-grub

- name: Copy Xmodmap
  copy:
    src: "files/Xmodmap"
    dest: "/home/dizzyd/.Xmodmap"
